increase proxy-buffer-size from 4k to 16k and make variable
akash-network/helm-charts pull request #117
Opened 2022-10-24 13:53 UTC by sacreman

2022-10-25 12:25 UTC, andy108369 requested changes

2022-10-25 12:25 UTC, andy108369 commented on charts/akash-ingress/templates/configmap.yaml
> +  proxy-buffer-size: "{{ .Values.proxy.buffersize }}"
The `proxy_busy_buffers_size` should be set to at least the same value if we want to change  `proxy_buffer_size` acc. to https://www.getpagespeed.com/server-setup/nginx/tuning-proxy_buffer_size-in-nginx

2022-10-27 14:19 UTC, sacreman commented on charts/akash-ingress/templates/configmap.yaml
> +  proxy-buffer-size: "{{ .Values.proxy.buffersize }}"
Not available: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#proxy-buffer-size

2022-10-27 14:24 UTC, andy108369 commented on charts/akash-ingress/templates/configmap.yaml
> +  proxy-buffer-size: "{{ .Values.proxy.buffersize }}"
ok, let's apply it and see if it does not cause any issues.

Refs.
- https://github.com/kubernetes/ingress-nginx/issues/363
- https://github.com/kubernetes/ingress-nginx/pull/364/files

2022-10-27 14:25 UTC, merged