Add ClusterIssuer to hostname-operator
akash-network/helm-charts pull request #196
Opened 2023-02-15 22:45 UTC by cloud-j-luna

This PR adds the support for ClusterIssuer and Issuer as well as setting the environment variables on the `akash-hostname-operator`.

2023-02-22 15:48 UTC, andy108369 requested changes

2023-02-22 15:48 UTC, andy108369 commented on charts/akash-hostname-operator/values.yaml
> +  repository: joaoluna/provider
I understand you've added it for sake of quick test and that's okay, but the repo needs to stay as-is.
So I am adding this as a non-merge placeholder, so it won't be merged by a mistake.

2023-02-22 16:29 UTC, boz approved these changes
:rocket:

2023-02-23 14:36 UTC, andy108369 commented on charts/akash-hostname-operator/values.yaml
> +  issuer:
is this for per-deployment issues?

2023-02-23 14:38 UTC, andy108369 requested changes
Will merge it once https://github.com/akash-network/provider/pull/86 is merged.

2023-02-27 18:16 UTC, boz reviewed
lgtm but I defer to @andy108369

2023-02-27 20:11 UTC, cloud-j-luna commented on charts/akash-hostname-operator/values.yaml
> +  issuer:
yes

2025-02-03 22:22 UTC, cloud-j-luna commented
This can be closed as it's extremely outdated no? @andy108369

2025-10-03 15:26 UTC, closed without merging