Update init.sh
akash-network/helm-charts pull request #290
Opened 2024-09-12 10:15 UTC by Dimokus88

Added Decloud Node Lab snapshot provider

2024-09-12 10:23 UTC, andy108369 requested changes
Please make sure to update chart version each time you update anything in the chart.
I'm Chart.yaml file.

2024-09-12 12:39 UTC, Dimokus88 commented
> Please make sure to update chart version each time you update anything in the chart.
> I'm Chart.yaml file.

You mean https://github.com/akash-network/helm-charts/blob/main/charts%2Fakash-node%2Fvalues.yaml ?

2024-09-16 16:58 UTC, Dimokus88 commented
> Please make sure to update chart version each time you update anything in the chart. I'm Chart.yaml file.

done

2024-09-16 20:36 UTC, andy108369 requested changes

2024-09-16 20:36 UTC, andy108369 commented on charts/akash-node/Chart.yaml
> +appVersion: 0.36.1
Please keep 0.36.0 here as is.
There were no new node releases yet. Akash network is still running at 0.36.0

https://github.com/akash-network/node/releases
https://github.com/akash-network/net/blob/main/mainnet/version.txt

2024-09-19 16:39 UTC, Dimokus88 commented on charts/akash-node/Chart.yaml
> +appVersion: 0.36.1
@andy108369 fix it!

2024-09-26 09:38 UTC, andy108369 commented
Thank you @Dimokus88 , I've fixed up multiple commits into one, with small cosmetic fixes.
Will be followed up here => https://github.com/akash-network/helm-charts/pull/292
Your commit is authored by you (you can see in the `Commits` tab there)

2024-09-26 09:38 UTC, closed without merging